#############################################################################
# Makefile for building: build/jeff
# Generated by qmake (3.1) (Qt 6.10.2)
# Project:  jeff.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile jeff.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -Ibuild -I/usr/lib64/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = jeff1.0.0
DISTDIR = /home/ice/playground/jeff/build/jeff1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib64 -Wl,-rpath-link,/usr/lib64
LIBS          = $(SUBLIBS) /usr/lib64/libQt6Widgets.so /usr/lib64/libQt6Gui.so /usr/lib64/libGLX.so /usr/lib64/libOpenGL.so /usr/lib64/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = mainwindow.cpp \
		codeeditor.cpp \
		highlighter.cpp \
		main.cpp build/moc_mainwindow.cpp \
		build/moc_codeeditor.cpp \
		build/moc_highlighter.cpp
OBJECTS       = build/mainwindow.o \
		build/codeeditor.o \
		build/highlighter.o \
		build/main.o \
		build/moc_mainwindow.o \
		build/moc_codeeditor.o \
		build/moc_highlighter.o
DIST          = /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_scxmlglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		jeff.pro mainwindow.hpp \
		codeeditor.hpp \
		highlighter.hpp \
		linenumberarea.hpp mainwindow.cpp \
		codeeditor.cpp \
		highlighter.cpp \
		main.cpp
QMAKE_TARGET  = jeff
DESTDIR       = build/
TARGET        = build/jeff


first: all
####### Build rules

build/jeff:  $(OBJECTS)  
	@test -d build/ || mkdir -p build/
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: jeff.pro /usr/lib64/qt6/mkspecs/linux-g++/qmake.conf /usr/lib64/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt6/mkspecs/common/unix.conf \
		/usr/lib64/qt6/mkspecs/common/linux.conf \
		/usr/lib64/qt6/mkspecs/common/sanitize.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt6/mkspecs/common/g++-base.conf \
		/usr/lib64/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt6/mkspecs/qconfig.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_httpserver.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_scxml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_scxmlglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_scxmlqml.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialbus.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt6/mkspecs/features/qt_config.prf \
		/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt6/mkspecs/features/toolchain.prf \
		/usr/lib64/qt6/mkspecs/features/default_pre.prf \
		/usr/lib64/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt6/mkspecs/features/default_post.prf \
		/usr/lib64/qt6/mkspecs/features/warn_on.prf \
		/usr/lib64/qt6/mkspecs/features/permissions.prf \
		/usr/lib64/qt6/mkspecs/features/qt.prf \
		/usr/lib64/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib64/qt6/mkspecs/features/resources.prf \
		/usr/lib64/qt6/mkspecs/features/moc.prf \
		/usr/lib64/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib64/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt6/mkspecs/features/uic.prf \
		/usr/lib64/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt6/mkspecs/features/file_copies.prf \
		/usr/lib64/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt6/mkspecs/features/exceptions.prf \
		/usr/lib64/qt6/mkspecs/features/yacc.prf \
		/usr/lib64/qt6/mkspecs/features/lex.prf \
		jeff.pro \
		/usr/lib64/libQt6Widgets.prl \
		/usr/lib64/libQt6Gui.prl \
		/usr/lib64/libQt6Core.prl
	$(QMAKE) -o Makefile jeff.pro
/usr/lib64/qt6/mkspecs/features/spec_pre.prf:
/usr/lib64/qt6/mkspecs/common/unix.conf:
/usr/lib64/qt6/mkspecs/common/linux.conf:
/usr/lib64/qt6/mkspecs/common/sanitize.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base.conf:
/usr/lib64/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt6/mkspecs/common/g++-base.conf:
/usr/lib64/qt6/mkspecs/common/g++-unix.conf:
/usr/lib64/qt6/mkspecs/qconfig.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_httpserver.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_scxml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_scxmlglobal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_scxmlqml.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_serialbus.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt6/mkspecs/features/qt_functions.prf:
/usr/lib64/qt6/mkspecs/features/qt_config.prf:
/usr/lib64/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt6/mkspecs/features/toolchain.prf:
/usr/lib64/qt6/mkspecs/features/default_pre.prf:
/usr/lib64/qt6/mkspecs/features/resolve_config.prf:
/usr/lib64/qt6/mkspecs/features/default_post.prf:
/usr/lib64/qt6/mkspecs/features/warn_on.prf:
/usr/lib64/qt6/mkspecs/features/permissions.prf:
/usr/lib64/qt6/mkspecs/features/qt.prf:
/usr/lib64/qt6/mkspecs/features/resources_functions.prf:
/usr/lib64/qt6/mkspecs/features/resources.prf:
/usr/lib64/qt6/mkspecs/features/moc.prf:
/usr/lib64/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib64/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt6/mkspecs/features/uic.prf:
/usr/lib64/qt6/mkspecs/features/unix/thread.prf:
/usr/lib64/qt6/mkspecs/features/qmake_use.prf:
/usr/lib64/qt6/mkspecs/features/file_copies.prf:
/usr/lib64/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt6/mkspecs/features/exceptions.prf:
/usr/lib64/qt6/mkspecs/features/yacc.prf:
/usr/lib64/qt6/mkspecs/features/lex.prf:
jeff.pro:
/usr/lib64/libQt6Widgets.prl:
/usr/lib64/libQt6Gui.prl:
/usr/lib64/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile jeff.pro

qmake_all: FORCE


all: Makefile build/jeff

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.hpp codeeditor.hpp highlighter.hpp linenumberarea.hpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.cpp codeeditor.cpp highlighter.cpp main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib64/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o build/moc_predefs.h /usr/lib64/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_mainwindow.cpp build/moc_codeeditor.cpp build/moc_highlighter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindow.cpp build/moc_codeeditor.cpp build/moc_highlighter.cpp
build/moc_mainwindow.cpp: mainwindow.hpp \
		build/moc_predefs.h \
		/usr/libexec/qt6/moc
	/usr/libexec/qt6/moc $(DEFINES) --include /home/ice/playground/jeff/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/ice/playground/jeff -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-suse-linux -I/usr/include/c++/15/backward -I/usr/lib64/gcc/x86_64-suse-linux/15/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/15/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include mainwindow.hpp -o build/moc_mainwindow.cpp

build/moc_codeeditor.cpp: codeeditor.hpp \
		highlighter.hpp \
		build/moc_predefs.h \
		/usr/libexec/qt6/moc
	/usr/libexec/qt6/moc $(DEFINES) --include /home/ice/playground/jeff/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/ice/playground/jeff -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-suse-linux -I/usr/include/c++/15/backward -I/usr/lib64/gcc/x86_64-suse-linux/15/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/15/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include codeeditor.hpp -o build/moc_codeeditor.cpp

build/moc_highlighter.cpp: highlighter.hpp \
		build/moc_predefs.h \
		/usr/libexec/qt6/moc
	/usr/libexec/qt6/moc $(DEFINES) --include /home/ice/playground/jeff/build/moc_predefs.h -I/usr/lib64/qt6/mkspecs/linux-g++ -I/home/ice/playground/jeff -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -I/usr/include/c++/15 -I/usr/include/c++/15/x86_64-suse-linux -I/usr/include/c++/15/backward -I/usr/lib64/gcc/x86_64-suse-linux/15/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-suse-linux/15/include-fixed -I/usr/x86_64-suse-linux/include -I/usr/include highlighter.hpp -o build/moc_highlighter.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/mainwindow.o: mainwindow.cpp mainwindow.hpp \
		codeeditor.hpp \
		highlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindow.o mainwindow.cpp

build/codeeditor.o: codeeditor.cpp linenumberarea.hpp \
		codeeditor.hpp \
		highlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/codeeditor.o codeeditor.cpp

build/highlighter.o: highlighter.cpp highlighter.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/highlighter.o highlighter.cpp

build/main.o: main.cpp mainwindow.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o main.cpp

build/moc_mainwindow.o: build/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindow.o build/moc_mainwindow.cpp

build/moc_codeeditor.o: build/moc_codeeditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_codeeditor.o build/moc_codeeditor.cpp

build/moc_highlighter.o: build/moc_highlighter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_highlighter.o build/moc_highlighter.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

